### ISSUE TITLE
w_scan2 is stuck in a loop scanning dvb-s2 astra23.5

### ISSUE THREAD

**Issue by ecw2-4** [stefantalpalaru/w_scan2#1]
Hello,

First of all, thanks for continuing the work on w_scan. I'm using the tool on a Gentoo box. I noticed that w_scan2 is stuck in a loop when I execute the following command:
`w_scan2 -f s -s S23E5 -D 1c -R 0 -E 0`
Stuck in a loop means the same transponder is being scanned over and over again. I have copied part of the output here: http://pastebin.com/LLSSLsfJ

How can I debug this further? What kind of information would you like to see?

**Comment by stefantalpalaru** [comment]
Do you have a local overlay where you can test a custom ebuild?

**Comment by ecw2-4** [comment]
Yes, I can do that.

**Comment by stefantalpalaru** [comment]
OK, I'll debug it and when I have a patch I'll push it to a new branch and give you a live ebuild to test it.

**Comment by ecw2-4** [comment]
OK great, thanks a lot.

**Comment by stefantalpalaru** [comment]
I made a 'debug' branch and I think we can iterate faster with a classic in-repo build:

```sh
git clone git@github.com:stefantalpalaru/w_scan2.git
cd w_scan2
git checkout --track origin/debug
```

Now you can build it:

```sh
./autogen.sh
./configure
make
```

And test the ./w_scan2 binary. If it doesn't fix the problem, please give me the verbose output generated by adding the '-v' argument.

**Comment by ecw2-4** [comment]
Unfortunately, this hasn't solved the issue. I added the output of `./w_scan2 -f s -s S23E5 -D 0c -R 0 -E 0 ` here: [output.txt](https://github.com/stefantalpalaru/w_scan2/files/859594/output.txt)

I will investigate further and let you know what other combinations of disecq position and initial satellite.

**Comment by ecw2-4** [comment]
I ran multiple tests with different combinations of options, disecq positions and initial scan files, but the above mentioned command is so far the only one that's looping.

**Comment by stefantalpalaru** [comment]
It would help me if you'd add the '-v' option to increase the output's verbosity.

**Comment by ecw2-4** [comment]
Sorry about that. Here's the output of the same command, except for the added -v
[output.txt](https://github.com/stefantalpalaru/w_scan2/files/877199/output.txt) (it's a rather large file)

**Comment by stefantalpalaru** [comment]
Please do a "git pull", a "make" and test it again.

**Comment by ecw2-4** [comment]
Thank you. This has solved the issue for me!

**Comment by stefantalpalaru** [comment]
Thanks for your help.

w_scan2-1.0.1 has been released and is available in my Gentoo overlay.
