### ISSUE TITLE
Support for VHF frequences in Poland (MUX8).

### ISSUE THREAD

**Issue by hetii** [stefantalpalaru/w_scan2#14]
Original w_scan tools don't scan VHF frequencies used in Poland by MUX8.
Please add VHF support for w_scan2 for PL.

Best Regards.

**Comment by stefantalpalaru** [comment]
VHF band III re-enabled for European DVB-T, due to this: https://tech.ebu.ch/docs/factsheets/ebu_tech_fs_use_of_band_III.pdf

Please test it.
