### ISSUE TITLE
How to scan only Free TV channels

### ISSUE THREAD

**Issue by muzena** [stefantalpalaru/w_scan2#17]
I want to only scan DVB-C Free TV channels.
Is this the right commands?

```
w_scan2 -fc -E N=0 -L -c HR > dvb-channels-dvb-c.xspf

w_scan2 -fc -E --encrypted-services=0 -L -c HR > dvb-channels-dvb-c.xspf
```

**Comment by stefantalpalaru** [comment]
You want `-E0` for that, so it should be `w_scan2 -fc -E0 -L -c HR > dvb-channels-dvb-c.xspf`.

**Comment by muzena** [comment]
This dosen't work, I think this options have problems.
When I normally scan without -E0 option, then is scan file ok.
But with this option, it include in scan file encrypted channels but not all channels like in full scan without -E0 option, and instead channels name there is 0021. service_id 11060, 0021. service_id 11070, 0021. service_id 11080... names

**Comment by stefantalpalaru** [comment]
We're using the channel's "scrambled" field to decide whether it's encrypted or not: https://github.com/stefantalpalaru/w_scan2/blob/6d0c1e9937c657d87a1ad5fef47748a531451434/src/scan.c#L3750

If that info is wrong, stick to the default of scanning all channels.
