### ISSUE TITLE
(dvb)scan initial-tuning-data problem

### ISSUE THREAD

**Issue by muzena** [stefantalpalaru/w_scan2#19]
I'm trying to generate initial tuning data for DVB-T/T2:
w_scan2 -c HR -x > dvb-t.txt
or
w_scan2 -ft -x -c HR > dvb-t.txt

Problem is that generated dvb-t.txt file is always empty, I don't know why.

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for the bug report.
