### ISSUE TITLE
w_scan2 alternately returns HD channels (only) and then non-HD channels (only)

### ISSUE THREAD

**Issue by dreamcat4** [stefantalpalaru/w_scan2#20]
[edited] I am still investigating this

After moving from `w_scan` to `w_scan2`, my USB stick finally returns HD channels. However I have to re-run it again to get the non-HD channels. In any single run, the tuner will either return HD or non HD channels only. And alternates between them.

This is not the only problem: Tvheadend only returns non-HD channels always. So my question is: how to solve this matter in `w_scan2` program. And then how to transfer this fixes into Tvheadend project?

This is one very popular stick:

https://www.linuxtv.org/wiki/index.php/Astrometa_DVB-T2

**Comment by dreamcat4** [comment]
Wheras using alternative program, `dvbv5-scan` it never finds any HD channels. It has same issue as described here:

https://webcache.googleusercontent.com/search?q=cache:4PXs4dH0a6UJ:https://www.tbsdtv.com/forum/viewtopic.php%3Ff%3D153%26t%3D9275+&cd=1&hl=en&ct=clnk&gl=nl&client=ubuntu

All the muxes configuration file seems fine... but the adapter needs to be switched into T2 mode for those T2 (HD) muxes. Otherwise it does not find anything. And this is what is broken. Yet somehow.... `w_scan2` program will find them on every other invokation.

It is almost as if it is setting some toggle bit each time. This is the beginning of `w_scan2` output:

```sh
w_scan2 -vvvv -c GB 
w_scan2 version 1.0.7 (compiled for DVB API 5.11)
using settings for UNITED KINGDOM
DVB aerial
DVB-T GB
scan type TERRESTRIAL, delivery system SYS_UNDEFINED, channellist 6
output format vdr-2.0
WARNING: could not guess your codepage. Falling back to 'UTF-8'
output charset 'UTF-8', use -C <charset> to override
Info: using DVB adapter auto detection.
   check Realtek RTL2832 (DVB-T):
           DVB-T
	/dev/dvb/adapter0/frontend0 -> TERRESTRIAL "Realtek RTL2832 (DVB-T)": good :-)
   check Panasonic MN88473:
           DVB-C ann.A
           DVB-T2
           DVB-T
	/dev/dvb/adapter0/frontend1 -> TERRESTRIAL "Panasonic MN88473": very good :-))

Using TERRESTRIAL frontend (adapter /dev/dvb/adapter0/frontend1)
-_-_-_-_ Getting frontend capabilities-_-_-_-_ 
Using DVB API 5.11
frontend 'Panasonic MN88473' supports
DVB-T2
INVERSION_AUTO
QAM_AUTO
TRANSMISSION_MODE_AUTO
GUARD_INTERVAL_AUTO
HIERARCHY_AUTO
FEC_AUTO
BANDWIDTH_AUTO not supported, trying 6/7/8 MHz.
FREQ (42.00MHz ... 1002.00MHz)
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_ 
   check Panasonic MN88473:
           DVB-C ann.A
           DVB-T2
           DVB-T
Scanning DVB-T...
Scanning 7MHz frequencies...
177500: (time: 00:01.119) 
        (0.770sec): SC (0x3)
        (0.770sec) signal
184500: (time: 00:01.959) 
191500: (time: 00:04.139) 
```

**Comment by dreamcat4** [comment]
Oh... it got all of them in 1 go this time.... I think I need to try a few more times. And see what is happening now.

**Comment by dreamcat4** [comment]
Have run 12 consecutive scans now today over the course of a few hours... It does not strictly alternate so therefore maybe its fluctuation in signal instead.

What is interesting though is that: with `-c GB` set the correct country the hit rate is only 25% chance of detecting any HD channels during a given run. Wereas if i omit the country code and it then defaults to `DE` automatically (even though I don't live in Germany)... then the detection rate for finding any HD channels in a given scan jumps up to about 75%. This was given 8 runs for UK country setting and 4 runs for DE country setting. (My country is UK)...

```sh
id@rpi-zero-w:~/w_scan2 $ grep service *.log | grep HD
wscan2.log.2.log:	service = QVC HD ((null))
wscan2.log.2.log:	service = QVC Beauty HD ((null))
wscan2.log.2.log:	service = CBeebies HD ((null))
wscan2.log.2.log:	service = BBC FOUR HD ((null))
wscan2.log.2.log:	service = QUEST HD ((null))
wscan2.no.country.vvvv.1.log:	service = BBC NEWS HD ((null))
wscan2.no.country.vvvv.1.log:	service = Channel 4+1 HD ((null))
wscan2.no.country.vvvv.1.log:	service = 4seven HD ((null))
wscan2.no.country.vvvv.1.log:	service = TJC HD ((null))
wscan2.no.country.vvvv.1.log:	service = RT HD ((null))
wscan2.no.country.vvvv.2.log:	service = BBC NEWS HD ((null))
wscan2.no.country.vvvv.2.log:	service = Channel 4+1 HD ((null))
wscan2.no.country.vvvv.2.log:	service = 4seven HD ((null))
wscan2.no.country.vvvv.2.log:	service = TJC HD ((null))
wscan2.no.country.vvvv.2.log:	service = RT HD ((null))
wscan2.no.country.vvvv.4.log:	service = QVC HD ((null))
wscan2.no.country.vvvv.4.log:	service = QVC Beauty HD ((null))
wscan2.no.country.vvvv.4.log:	service = CBeebies HD ((null))
wscan2.no.country.vvvv.4.log:	service = BBC FOUR HD ((null))
wscan2.no.country.vvvv.4.log:	service = QUEST HD ((null))
wscan2.vvvv.4.log:	service = QVC HD ((null))
wscan2.vvvv.4.log:	service = QVC Beauty HD ((null))
wscan2.vvvv.4.log:	service = CBeebies HD ((null))
wscan2.vvvv.4.log:	service = BBC FOUR HD ((null))
wscan2.vvvv.4.log:	service = QUEST HD ((null))
id@rpi-zero-w:~/w_scan2 $ ls *log
config.log        wscan2.log.2.log  wscan2.log.4.log              wscan2.no.country.vvvv.2.log  wscan2.no.country.vvvv.4.log  wscan2.vvvv.2.log  wscan2.vvvv.4.log
wscan2.log.1.log  wscan2.log.3.log  wscan2.no.country.vvvv.1.log  wscan2.no.country.vvvv.3.log  wscan2.vvvv.1.log             wscan2.vvvv.3.log
id@rpi-zero-w:~/w_scan2 $ ls -l *log
-rw-r--r-- 1 id id  20765 Jan 30 17:02 config.log
-rw-r--r-- 1 id id  98114 Feb 25 11:50 wscan2.log.1.log
-rw-r--r-- 1 id id 118130 Feb 25 12:29 wscan2.log.2.log
-rw-r--r-- 1 id id 107083 Feb 25 12:55 wscan2.log.3.log
-rw-r--r-- 1 id id  85541 Feb 25 13:13 wscan2.log.4.log
-rw-r--r-- 1 id id 433782 Feb 25 18:25 wscan2.no.country.vvvv.1.log
-rw-r--r-- 1 id id 412064 Feb 25 18:36 wscan2.no.country.vvvv.2.log
-rw-r--r-- 1 id id 354573 Feb 25 19:04 wscan2.no.country.vvvv.3.log
-rw-r--r-- 1 id id 337019 Feb 25 19:13 wscan2.no.country.vvvv.4.log
-rw-r--r-- 1 id id 694406 Feb 25 14:16 wscan2.vvvv.1.log
-rw-r--r-- 1 id id 615318 Feb 25 14:44 wscan2.vvvv.2.log
-rw-r--r-- 1 id id 555428 Feb 25 17:25 wscan2.vvvv.3.log
-rw-r--r-- 1 id id 550803 Feb 25 17:49 wscan2.vvvv.4.log
id@rpi-zero-w:~/w_scan2 $ ls -l *log
```

Perhaps I need to change my antenna cabling and try again.

**Comment by stefantalpalaru** [comment]
Interesting. We should check for changes in UK frequencies.

**Comment by dreamcat4** [comment]
There has been changes due to 700mhz clearance project (for 5g etc). This has been happening during last 4 years period. And this has affected some of the muxes moved. Typically 2 muxes for any single transmitter site. However when I check the master branch of crazy cat's dvt-scan-tables on github it seems they already have updated and included the new muxes there. So I think that is ok...

My main issue is tvheadend because it never detects anything whatsoever on those muxes. And the new `dvbv5-scan` api (which is supposed to include T2 support). I have scanned with `dvbv5-scan` a couple of times and it did not find any HD channels. Really hit and miss. I shall need to check and compare this antenna signal against my TV's tuner. And then come back later on.

**Comment by Marco-GG** [comment]
Just noticed this (probably very late). 

@dreamcat4 does using "-F" and "-t 3" options helps to fix your issue? As far I remember in mpeg ts all programs information is located in the PAT and PMT descriptors. I'm not sure of how w_scan2 handles programs detection but I would expect that it scan for both as the later is required in order to fully create channels.conf data. My point is that a low snr or signal strength may explain this issue (supposing that PMT are over different PIDs) so giving some extra time to tuning and filtering may help.

Still, very weird that not setting your country your situation improves (maybe there is a wrong parameter in the GB setup?)

**Comment by dreamcat4** [comment]
@Marco-GG thank you for this suggestion. I will be running some new scans today and see how consistent they are with `-F -t 3` flags, if they are same from scan to scan.

BTW is there any other flags I should be using? Perhaps I should output in a specific format, so then the output can be feed into `dvbv5-scan` ? I am not sure how to do this.

Anyhow thank you for such helpful comment. Have a good day.

**Comment by Marco-GG** [comment]
What you probably are looking for is the channel freqs list, doesn't it? If so, I think you can get it with "-x" argument (seems to not be working well for me though).

Anyway, I never used dvbv5-scan but I noticed something:

Seems that  the frontend that supports DVB-T2 in your system is the second one (i.e. "1"). So, when you run dvbv5-scan do you set "-f 1" as argument?

**Comment by dreamcat4** [comment]
OK my multiple scans script has completed. Here is a summary of the total number of channels found during each scan. They were taken one after the other with no pause. The scan types were interleaved in the following sequence: `GB` then `GB -vvvv` then `DE` then `DE -vvvv`. What seems to be happening is that the number of channels is heavily dependant on the time of the scan. With the signal fluctuating significantly between only 17 and 105 channels detected.

This is the same for all the scan types except the `DE`. So what seems to be happening is that if you select `DE` country with also the `-vvvv` extra verbose flag. Then that maybe slows it down enough to detect a similar number of channels as `GB`. However if you run as `DE` country without `-vvvv` (or omit the `-c` flag, which then chooses for you). Then it seems that the scan misses more channels.

```sh
 81 Channels Found - Thu 12 Mar 19:47:21 GMT 2020 running scan #1 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
 81 Channels Found - Thu 12 Mar 20:06:18 GMT 2020 running scan #1 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
105 Channels Found - Thu 12 Mar 20:27:34 GMT 2020 running scan #1 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
 69 Channels Found - Thu 12 Mar 20:41:45 GMT 2020 running scan #1 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

 95 Channels Found - Thu 12 Mar 20:52:40 GMT 2020 running scan #2 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
 95 Channels Found - Thu 12 Mar 21:13:24 GMT 2020 running scan #2 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
103 Channels Found - Thu 12 Mar 21:34:05 GMT 2020 running scan #2 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
 95 Channels Found - Thu 12 Mar 21:47:02 GMT 2020 running scan #2 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

104 Channels Found - Thu 12 Mar 22:00:42 GMT 2020 running scan #3 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
104 Channels Found - Thu 12 Mar 22:20:49 GMT 2020 running scan #3 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
 97 Channels Found - Thu 12 Mar 22:41:19 GMT 2020 running scan #3 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
104 Channels Found - Thu 12 Mar 22:53:20 GMT 2020 running scan #3 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

103 Channels Found - Thu 12 Mar 23:06:40 GMT 2020 running scan #4 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
103 Channels Found - Thu 12 Mar 23:26:56 GMT 2020 running scan #4 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
 96 Channels Found - Thu 12 Mar 23:47:40 GMT 2020 running scan #4 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
103 Channels Found - Thu 12 Mar 23:58:26 GMT 2020 running scan #4 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

103 Channels Found - Fri 13 Mar 00:12:11 GMT 2020 running scan #5 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
103 Channels Found - Fri 13 Mar 00:33:08 GMT 2020 running scan #5 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
 62 Channels Found - Fri 13 Mar 00:53:40 GMT 2020 running scan #5 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
103 Channels Found - Fri 13 Mar 01:03:07 GMT 2020 running scan #5 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

103 Channels Found - Fri 13 Mar 01:18:43 GMT 2020 running scan #6 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
103 Channels Found - Fri 13 Mar 01:39:48 GMT 2020 running scan #6 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
 73 Channels Found - Fri 13 Mar 02:04:30 GMT 2020 running scan #6 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
  - Channels Found - Fri 13 Mar 02:15:02 GMT 2020 running scan #6 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

103 Channels Found - Fri 13 Mar 02:28:19 GMT 2020 running scan #7 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
102 Channels Found - Fri 13 Mar 02:53:23 GMT 2020 running scan #7 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
 79 Channels Found - Fri 13 Mar 03:14:02 GMT 2020 running scan #7 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
103 Channels Found - Fri 13 Mar 03:26:25 GMT 2020 running scan #7 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

 79 Channels Found - Fri 13 Mar 03:27:29 GMT 2020 running scan #8 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
 73 Channels Found - Fri 13 Mar 03:48:32 GMT 2020 running scan #8 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
 25 Channels Found - Fri 13 Mar 04:08:31 GMT 2020 running scan #8 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
103 Channels Found - Fri 13 Mar 04:18:29 GMT 2020 running scan #8 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/

 17 Channels Found - Fri 13 Mar 04:19:26 GMT 2020 running scan #9 for GB saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/
 17 Channels Found - Fri 13 Mar 04:43:42 GMT 2020 running scan #9 for GB -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/GB/vvvv/
 66 Channels Found - Fri 13 Mar 04:58:50 GMT 2020 running scan #9 for DE saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/
 78 Channels Found - Fri 13 Mar 05:08:39 GMT 2020 running scan #9 for DE -vvvv saving to /home/id/wscan2-attic-logs/12th-march/evening/DE/vvvv/


~/wscan2-attic-logs/12th-march/evening $ grep -R -o "dumping lists.*" * | sort
GB/wscan2.1.log:dumping lists (81 services)
GB/wscan2.2.log:dumping lists (105 services)
GB/wscan2.3.log:dumping lists (104 services)
GB/wscan2.4.log:dumping lists (103 services)
GB/wscan2.5.log:dumping lists (103 services)
GB/wscan2.6.log:dumping lists (103 services)
GB/wscan2.7.log:dumping lists (103 services)
GB/wscan2.8.log:dumping lists (79 services)
GB/wscan2.9.log:dumping lists (17 services)

GB/vvvv/wscan2.1.log:dumping lists (81 services)
GB/vvvv/wscan2.2.log:dumping lists (105 services)
GB/vvvv/wscan2.3.log:dumping lists (104 services)
GB/vvvv/wscan2.4.log:dumping lists (103 services)
GB/vvvv/wscan2.5.log:dumping lists (103 services)
GB/vvvv/wscan2.6.log:dumping lists (103 services)
GB/vvvv/wscan2.7.log:dumping lists (102 services)
GB/vvvv/wscan2.8.log:dumping lists (73 services)
GB/vvvv/wscan2.9.log:dumping lists (17 services)

DE/wscan2.1.log:dumping lists (105 services)
DE/wscan2.2.log:dumping lists (93 services)
DE/wscan2.3.log:dumping lists (97 services)
DE/wscan2.4.log:dumping lists (96 services)
DE/wscan2.5.log:dumping lists (62 services)
DE/wscan2.6.log:dumping lists (73 services)
DE/wscan2.7.log:dumping lists (79 services)
DE/wscan2.8.log:dumping lists (25 services)
DE/wscan2.9.log:dumping lists (66 services)

DE/vvvv/wscan2.1.log:dumping lists (69 services)
DE/vvvv/wscan2.2.log:dumping lists (105 services)
DE/vvvv/wscan2.3.log:dumping lists (104 services)
DE/vvvv/wscan2.4.log:dumping lists (103 services)
DE/vvvv/wscan2.5.log:dumping lists (103 services)
DE/vvvv/wscan2.6.log:dumping lists (103 services)
-
DE/vvvv/wscan2.9.log:dumping lists (78 services)
```

**Comment by dreamcat4** [comment]
@Marco-GG Hey there again....

> Seems that the frontend that supports DVB-T2 in your system is the second one (i.e. "1"). So, when you run dvbv5-scan do you set "-f 1" as argument?

I take your advice fully... not knowing anything myself! And YES! The specifal magic seems to work now by using this 2 commands:

```sh
sudo w_scan2 -F -t 3 -x -c GB 1> wscan2-format-x
# only 82 services found that time. Because the local signal quality changes so greatly. from minute to minute.

# But maybe that unlucky scan does not matter because the output file is just the list of few muxes. Rather than all the channels themselves
$ cat wscan2-format-x 
#------------------------------------------------------------------------------
# file automatically generated by w_scan2
# (https://github.com/stefantalpalaru/w_scan2)
#! <w_scan> 1.0.7 3 1 TERRESTRIAL GB </w_scan>
#------------------------------------------------------------------------------
# location and provider: <add description here>
# date (yyyy-mm-dd)    : 2020-03-14
# provided by (opt)    : <your name or email here>
#
# T[2] <freq> <bw> <fec_hi> <fec_lo> <mod> <tm> <guard> <hi> [plp_id] [# comment]
#------------------------------------------------------------------------------
T 482000000 8MHz AUTO AUTO     AUTO AUTO AUTO AUTO	# South
T 506000000 8MHz  3/4 NONE    QAM64   8k 1/32 NONE	# South
T2         0 AUTO AUTO NONE     AUTO AUTO AUTO NONE
T2         0 AUTO AUTO NONE     AUTO AUTO AUTO NONE
T2         0 AUTO AUTO NONE     AUTO AUTO AUTO NONE
T 498000000 8MHz AUTO AUTO     AUTO AUTO AUTO AUTO	# South
T 522000000 8MHz AUTO AUTO     AUTO AUTO AUTO AUTO	# South
T2 474000000 8MHz AUTO AUTO     AUTO AUTO AUTO AUTO	# South


sudo dvbv5-scan  --cc=GB -a 0 -f 1 --input-format=CHANNEL --output-format=DVBV5 -T 10 wscan2-format-x
```

And then `dvbv5-scan` actually found the HD channels. Great! The default output format was `--output-format=DVBV5` however there are 2 other output formats `VDR, CHANNEL, ZAP`.

**Comment by dreamcat4** [comment]
The next challenge is to figure out how to get the output from `dvbv5scan` program input into `tvheadend` server. So that `tvheadend` itself can finally detect these `HD` / `t2` channels. Which left on it's own devices it always fails to find them.

So if there is any other help for that stage. Then I would be so much happier.

Perhaps `tvheadend` is otherwise broken. If this cannot be done. So then the settings of `dvbv5-scan` and `wscan2` can be a help to show that it is not exactly an issue of only the hardware itself. Or the antenna.

Perhaps what else I should do is a blind scan of `dvbv5-scan` using the public CrazyCat github / muxes listed in the `dvb-scan-files` repo. This is also the same 'muxes' input which TvHeadend is starting point for it's own scans.

**Comment by dreamcat4** [comment]
The reason I say that is because other user has reported about only making T2 work if the Muxes are manually entered (and correctly). So I can now test this theory on my own setup. To see if I have same issue. Or if it is something else the problem.

Thanks again for coming back to offer suggestion and help. More than just once. As otherwise I would 100% have given up long times ago on this. Thinking it's impossible.

**Comment by stefantalpalaru** [comment]
> the local signal quality changes so greatly. from minute to minute

Try an amplifier. I'm having good results with a couple of simple ones, even though they amplify noise as much as they amplify signals: Meliconi AMP20 and Meliconi AMP 20 Mini.

**Comment by Marco-GG** [comment]
Sorry, I forgot to check github messages this week.

> The next challenge is to figure out how to get the output from `dvbv5scan` program input into `tvheadend` server. So that `tvheadend` itself can finally detect these `HD` / `t2` channels. Which left on it's own devices it always fails to find them.
> 
> So if there is any other help for that stage. Then I would be so much happier.
> 
> Perhaps `tvheadend` is otherwise broken. If this cannot be done. So then the settings of `dvbv5-scan` and `wscan2` can be a help to show that it is not exactly an issue of only the hardware itself. Or the antenna.
> 
> Perhaps what else I should do is a blind scan of `dvbv5-scan` using the public CrazyCat github / muxes listed in the `dvb-scan-files` repo. This is also the same 'muxes' input which TvHeadend is starting point for it's own scans.

First of all: It's the first time I've used tvheadend. So what I'm gonna mention comes from a rookie of the application :P 

IMO if you are having problem with DVB-T2 scan in tvheadend it's probably due to the same issue you had with dvbv5-scan. With some luck a similar "fix" may work in this case too:

This is the view of my adapters in tvheadend:

![image](https://user-images.githubusercontent.com/9803355/77379823-6eb31080-6d58-11ea-8240-f2dc5b797354.png)

The second folder in the tree is the adapter and the branch of it are the frontends (the magic number "1" you used in your command). 

Unfortunately all my devices have one frontend so I can't show you an example that will resemble your configuration. Anyway, the idea is that in order to do a similar hack as you did with dvbv5-scan you should disable the frontend you don't want to use. This is:

![image](https://user-images.githubusercontent.com/9803355/77380574-2694ed80-6d5a-11ea-8aca-fb80d2632939.png)

(Remember to hit "Save" button after you disable it!).

Yet again, bare in mind that disabling the frontend is probably not the most efficient solution (but definitely the first step you should do!). I think that the "PRO" solution is to create two different networks for each frontend, that way you may will probably have an extra frontend for streaming content (supposing that frontend "0" in your device can be used simultaneously with frontend "1").

Hope something of what I said makes any sense for you or at least help you with tvheadend setup.

**Comment by dreamcat4** [comment]
It makes a great deal of sense and thank you so much for explaining this! Also am grateful for keeping this issue going and stay open for such a long time. As many of us are busy with other matters between.

Been hoping to get back to this. So now I can gladly be trying this out next. Currently my version of tvheadend is the latest 'stable' version 4.2.8 so was otherwise also planning to try switch to the master development branch. In case there is newer code added that was missed from stable branch. However I am also in doubt if that matter much. It might not be necessary. Or make a difference.

Instead I will try your suggestion before that now. Just we have those other distractions to deal with (as everybody). Which is not anything regarding this issue. But I thank you & wish you well during these times.

A fantastic help.
