### ISSUE TITLE
w_scan2 doesn't accept the -k option

### ISSUE THREAD

**Issue by rolfep** [stefantalpalaru/w_scan2#21]
Hi.
I'm running up-to-date Mageia release 7 (Official) for x86_64.  First, I installed the distro rpm of your program, ran into this issue, filed a bug and was asked to report here.
https://bugs.mageia.org/show_bug.cgi?id=26497

To test further, I cloned the code with git and built according to the project page with no errors I can see.  In summary:

[rolf@x570i git]$ git clone https://github.com/stefantalpalaru/w_scan2.git w_scan2
Cloning into 'w_scan2'...
...
Resolving deltas: 100% (389/389), done.
[rolf@x570i git]$ cd w_scan2/
[rolf@x570i w_scan2 (master)]$ ls
autogen.sh*  ChangeLog  configure.ac  COPYING  doc/  INSTALL  Makefile.am  packaging/  README.md  src/
[rolf@x570i w_scan2 (master)]$ ./autogen.sh
Preparing the w_scan2 build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.16.1
Found GNU Libtool version 2.4.6

Automatically preparing build ... done

The w_scan2 build system is now prepared.  To build here, run:
  ./configure
  make
[rolf@x570i w_scan2 (master)]$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
...
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
[rolf@x570i w_scan2 (master)]$ make
...
gcc -Wall -Wextra -Wno-comment -Wswitch-default -Wno-unused-parameter -g -O2 -lrt  -o w_scan2 src/atsc_psip_section.o src/countries.o src/descriptors.o src/diseqc.o src/dump-dvbscan.o src/dump-vdr.o src/dump-xine.o src/dump-mplayer.o src/dump-vlc-m3u.o src/dvbscan.o src/lnb.o src/parse-dvbscan.o src/satellites.o src/scan.o src/section.o src/tools.o src/emulate.o src/dump-xml.o src/iconv_codes.o src/char-coding.o  

[rolf@x570i w_scan2 (master)]$ ./w_scan2 -c US -k > channels.dvb  
./w_scan2 -c US -k 
./w_scan2: invalid option -- 'k'

*Note:  the syntax I used follows the man page and project page examples.

Thanks.

**Comment by stefantalpalaru** [comment]
Looks like Kaffeine output was removed 6 years ago: https://github.com/stefantalpalaru/w_scan2/blob/895870e0497f33ce383b00fdf0a6b1c230657c6e/ChangeLog#L136

We just need to update the manual page and README.

**Comment by stefantalpalaru** [comment]
Documentation updated.
