### ISSUE TITLE
Transponder is not scanned / no Channels found

### ISSUE THREAD

**Issue by xforze** [stefantalpalaru/w_scan2#25]
Hello!

I want to scan the channels on Astra 4A & SES 5 at 4.9°E. It seems that at least one Transponder is not scanned as Im missing the channels from it.
The freq is: 11766 H, you will find it on: https://www.lyngsat.com/Astra-4A-and-SES-5.html
It seems that w_scan2 knows about this Transponder as it is listet in the console output:
```
# cat log | grep -i 11766
trying 'S  f = 11766 kHz H SR = 27500  3/4 0,35  QPSK  (0:0:0)'
        new transponder: (S  f = 11766 kHz H SR = 27500  3/4 0,35  QPSK  (85:85:12)) 0x4043
        new transponder: (S2 f = 11766 kHz H SR = 27500  2/3 0,20  8PSK  (85:68:12)) 0x4043
tune to: S  f = 11766 kHz H SR = 27500  3/4 0,35  QPSK  (85:85:12) (time: 08:19.922) 
tune to: S  f = 11766 kHz H SR = 27500 AUTO 0,AUTO  QPSK  (85:85:12) (time: 08:25.310)  (no signal)
tune to: S2 f = 11766 kHz H SR = 27500  2/3 0,20  8PSK  (85:68:12) (time: 10:45.922) 
        S2 f = 11766 kHz H SR = 27500  2/3 0,20  8PSK  (85:68:12) : updating network_id -> (85:85:12)
```

If im doing a init scan, this Transponder is not listed in the output file. 
The same with the channels.conf file if Im doing a '-G' scan.

Any ideas what could be wrong ?

Cheers!

**Comment by stefantalpalaru** [comment]
Could its signal be too weak?

**Comment by xforze** [comment]
Hi!

I tried to tune this Transponder with szap-s2 and this seems to be working:

```
# szap-s2 -c t.conf -n 1
reading channels from file 't.conf'
zapping to 1 'TEST;Test':
delivery DVB-S2, modulation 8PSK
sat 0, frequency 11766 MHz H, symbolrate 27500000, coderate 2/3, rolloff 0.35
mis -1, vpid 0x03e9, apid 0x03ea, sid 0x0000
using '/dev/dvb/adapter0/frontend0' and '/dev/dvb/adapter0/demux0'
status 00 | signal b0a3 | snr 0000 | ber 00000001 | unc fffffffe | 
status 1f | signal b0a3 | snr 0082 | ber 00000001 | unc fffffffe | FE_HAS_LOCK
status 1f | signal ee13 | snr 0082 | ber 00000001 | unc fffffffe | FE_HAS_LOCK
status 1f | signal ee13 | snr 0082 | ber 00000001 | unc fffffffe | FE_HAS_LOCK
status 1f | signal ee13 | snr 0084 | ber 00000001 | unc fffffffe | FE_HAS_LOCK
```

My Satellite Receiver (VU Box) shows Signal strength of 80% on a channel from that Transponder.

Would be a more verbose output helpful ?
I could provide a pidscan from that Transponder as well if needed.


Cheers, Thomas

**Comment by stefantalpalaru** [comment]
You can increase w_scan2's logging verbosity with one or two `-v` options.

**Comment by xforze** [comment]
Hi!
Here is the verbose log file with the channel config file **ses.conf**. As you can see, there is no channel listed from Transponder 11766 H 275000 2/3.
I added the pidscan output as well, there you will find an Entry **Service_name: "Unian TV"  -- Charset: Latin alphabet**. This is one from the missing Channels from the Transponder.

[logs.tar.gz](https://github.com/stefantalpalaru/w_scan2/files/4881021/logs.tar.gz)

Cheers, Thomas

**Comment by stefantalpalaru** [comment]
The problem is here:

```text
tune to: S  f = 11766 kHz H SR = 27500  3/4 0,35  QPSK  (85:85:12) (time: 08:02.100)
DiSEqC: uncommitted switch pos 0
diseqc_send_msg:431: DiSEqC: e0 10 39 f0 00 00
DiSEqC: switch pos 0, 18V, hiband (index 3)
diseqc_send_msg:431: DiSEqC: e0 10 38 f3 00 00
----------no signal----------
tune to: S  f = 11766 kHz H SR = 27500 AUTO 0,AUTO  QPSK  (85:85:12) (time: 08:07.480)  (no signal)
DiSEqC: uncommitted switch pos 0
diseqc_send_msg:431: DiSEqC: e0 10 39 f0 00 00
DiSEqC: switch pos 0, 18V, hiband (index 3)
diseqc_send_msg:431: DiSEqC: e0 10 38 f3 00 00
----------no signal----------
```

How about increasing the tuning timeout with `-t 3`?

**Comment by xforze** [comment]
Hi!
The time Parameter didnt any change.
I got it working by doing the following Change in sattelites.dat and recompiled w_scan2:
Old Line:
{5, 11766, 0, 27500, 3 , 0, 0 },              // ASTRA 4A && SES 5            ; (85   , 86   ,12   )
New Line:
{6, 11766, 0, 27500, 3 , 0, 0 },              // ASTRA 4A && SES 5            ; (85   , 86   ,12   )
(I changed the 5 to 6)

Now I get the channels listed in the output file:
```
# cat ses.conf | grep 11766
1+1(1plus1 Media):11766:h:0:27500:1001:1002:6100
1+1 HD(1plus1 Media):11766:h:0:27500:1011:1012:6101
Kvartal TV(1plus1 Media):11766:h:0:27500:1081:1082:6108
TET(1plus1 Media):11766:h:0:27500:1101:1102:6110
Plus Plus(1plus1 Media):11766:h:0:27500:1121:1122:6112
Bigudi(1plus1 Media):11766:h:0:27500:1141:1142:6114
2+2(1plus1 Media):11766:h:0:27500:1201:1202:6120
1+1 International(1plus1 Media):11766:h:0:27500:1251:1252:6125
```
Im not sure what is the first Parameter in satellites.dat for but I guess its the DVB System (DVB-S / DVB-S2) ?
I double checked it as well, with 5 at the beginning, no channels from that Transponder are listed. 
With 6 at the beginning, the channels are written to the .conf file.

Cheers, Thomas

**Comment by andimik** [comment]
The solution was your initial posting. The console output described the transponder twice. In DVB-S and then in DVB-S2 (the later is correct).

So, I fear w_scan2 ignored the second parameter and only used the first one (DVB-S).

**Comment by xforze** [comment]
Hi,
It seems to me that w_scan2 tunes to the correct transponder with correct settings as you can see in my initial post
(when no Channels are found):
```
tune to: S2 f = 11766 kHz H SR = 27500  2/3 0,20  8PSK  (85:68:12) (time: 10:45.922) 
        S2 f = 11766 kHz H SR = 27500  2/3 0,20  8PSK  (85:68:12) : updating network_id -> (85:85:12)
```
Its tuned to: **DVB-S2**, Freq = 11766 kHz, Pol= H, SR = 27500, FEC =  2/3
I guess this must be received from a previous Transponder Stream, I found in the Log Ouput:
 `new_transponders(017): S2 f = 11766 kHz H SR = 27500  3/4 0,35  QPSK  (0:85:0)`

But for somehow, no channels are found.

Cheers, Thomas

**Comment by andimik** [comment]
But I guess this comes from a wrong parameter in the NIT of one in the other transponders.
