### ISSUE TITLE
dvbv5-scan fails while parsing DVBV5 channel config file

### ISSUE THREAD

**Issue by optimosfet** [stefantalpalaru/w_scan2#34]
Hi,

dvbv5-scan (>= v1.20.0) fails while parsing channel config files (dvbv5 format), created by w_scan2 (>= v1.0.11).

w_scan2 dumps the value for the modulation parameter differently than expected by dvbv5-scan utility:
https://github.com/stefantalpalaru/w_scan2/blob/0e035c68d1a832e597f9678bb05b7398cdc79703/src/dvbscan.c#L245-L255

https://git.linuxtv.org/v4l-utils.git/tree/lib/libdvbv5/dvb-v5.c?h=stable-1.20#n70
```
const char *fe_modulation_name[15] = {
	[APSK_16] =  "APSK/16",
	[APSK_32] =  "APSK/32",
	[DQPSK] =    "DQPSK",
	[PSK_8] =    "PSK/8",
	[QAM_4_NR] = "QAM/4_NR",
	[QAM_16] =   "QAM/16",
	[QAM_32] =   "QAM/32",
	[QAM_64] =   "QAM/64",
	[QAM_128] =  "QAM/128",
	[QAM_256] =  "QAM/256",
	[QAM_AUTO] = "QAM/AUTO",
	[QPSK] =     "QPSK",
	[VSB_8] =    "VSB/8",
	[VSB_16] =   "VSB/16",
	[14] = NULL,
};
```

**Comment by stefantalpalaru** [comment]
Should be fixed by https://github.com/stefantalpalaru/w_scan2/commit/22102969082ad0533facbb3d96f47972104793af

Please test it.

**Comment by optimosfet** [comment]
@stefantalpalaru
I can confirm this, at least this also applies to my test environment.

Thx for your prompt fix.
