### ISSUE TITLE
using w-scan2 for 124E and 128E

### ISSUE THREAD

**Issue by f520k510** [stefantalpalaru/w_scan2#35]
I am looking for a way to use w-scan2 to scan for 124E and 128E for Japanese sky perfec tv.
The tp are in dvb-s2 and 8psk format.
Is there any way I can add 128e and 124e to the satellite list?
Or how can I edit satellite list of an existing one to match the tp of 124e and 128e?

Thanks.

**Comment by stefantalpalaru** [comment]
@jmwislez is your man, for that.

**Comment by jmwislez** [comment]
I had not realized that the satellite list from kingofsat.net (that I used to generate the updated initial tuning list) has a gap between 75E and 140W.  Do you know of a similar site that lists the satellites for your area of the world?
As a quick fix, you can recover the old version of src/satellites.dat (prior to March 4, 2021) and recompile with that.
This list is 9 years old, however.  Can you report whether this works for you?  Depending on your answer, I will either try to grab the missing satellites from another source, or I will hard-code the missing satellites from the previous list in the new satellites.dat list.

**Comment by f520k510** [comment]
Thanks for your replies.
There has been update to tp recent years and I suspect the list is too old.
I have an updated list for scan-s2.  I wonder if you can generate file from 
Thanks.
This list is manually made checking on my stb with updated channels.
I am not aware of sites with updated tp for 124e and 128e.
Also, I am not familiar with w_scan2 -l options.  Seems like there is only fixed typed to choose, unlike for szap-sj which also accept -l low,high,switch for customised lnb.  For 124e and 128e, they use 11300,11300,10000 for 124e, and 11300,11300,20000 for 128e.  
I would also appreciate if a fixed  identifier can be set for 128e and 124e, for example JCSAT3A for 128E, and JCSAT4A for 124E.
Maybe I should have request this feature in the dvb5-zap repository, but adding flexibility for customised lnb is a great feature, I think.  I know scan-s2 and szap-s2(j) also implements that.  My ultimate goal is to request and have the same -l function in DVBv5-zap, so I can use it in my rirakurun, where I can use -l JCSAT3A or -JCSAT4A, commands read from its channels.yml file.
Then I can change channels on all channels on both 124E and 128E.   

So, here is a summary of my requests:
1.  adding 124e and 128e tp to satellite list.
2.  (optional)adding missing satelites
3.  -l to allow low,high,switch as parameters

124E
S2 12268000 V 23303000 3/5 AUTO 8PSK
S2 12448000 V 23303000 3/5 AUTO 8PSK
S2 12568000 V 23303000 3/5 AUTO 8PSK
S2 12583000 H 23303000 3/5 AUTO 8PSK
S2 12598000 V 23303000 3/5 AUTO 8PSK
S2 12613000 H 23303000 3/5 AUTO 8PSK
S2 12628000 V 23303000 3/5 AUTO 8PSK
S2 12643000 H 23303000 3/5 AUTO 8PSK
S2 12673000 H 23303000 3/5 AUTO 8PSK
S2 12688000 V 23303000 3/5 AUTO 8PSK
S2 12703000 H 23303000 3/5 AUTO 8PSK
S2 12718000 V 23303000 3/5 AUTO 8PSK
S2 12733000 H 23303000 3/5 AUTO 8PSK

128E
S2 12523000 H 23303000 3/5 AUTO 8PSK
S2 12568000 V 23303000 3/5 AUTO 8PSK
S2 12583000 H 23303000 3/5 AUTO 8PSK
S2 12598000 V 23303000 3/5 AUTO 8PSK
S2 12613000 H 23303000 3/5 AUTO 8PSK
S2 12643000 H 23303000 3/5 AUTO 8PSK
S2 12673000 H 23303000 3/5 AUTO 8PSK
S2 12688000 V 23303000 3/5 AUTO 8PSK
S2 12703000 H 23303000 3/5 AUTO 8PSK
S2 12718000 V 23303000 3/5 AUTO 8PSK
S2 12733000 H 23303000 3/5 AUTO 8PSK



Your help will be much appreciated.

**Comment by andimik** [comment]
You can try https://www.lyngsat.com/
https://www.flysat.com/

**Comment by f520k510** [comment]
I haven't been clear about the LNBF for 124E and 128E.  It has been 11200 for most Japanese users.  So, the identifier of JCSAT3A should be of values (lof1,lof2,sw)=(11200,11200,20000) and JCSAT4A (lof1,lof2,sw)=(11200,11200,10000)
My hope is that there values can be store somewhere in the code so we can easily change to my lnb (11300,11300,10000) or (11300,11300,20000)    

That said, for the functions I will use, to generate init file for dvbv5-scan, I don't mind if the JCSAT3A and JCSAT4A identifier for lnb types are not implemented, as long as -l options accepts low,[high],[sw] would be good enough.   Thanks.

**Comment by f520k510** [comment]
I downloaded v1.0.11 from git ppa and there were 2 versions.  1.0.12 and 1.0.11.
I install it and w_scan2 -s ?
and 124E and 128E were not in the list.
I am running ubuntu and it seems the only available old version for ubuntu is 1.0.11.

**Comment by jmwislez** [comment]
> 
> 
> You can try https://www.lyngsat.com/
> https://www.flysat.com/

Thank you, but unfortunately these are not straightforward to parse.  Did you find on these sites the possibility to download raw data, like kingofsat has?

**Comment by jmwislez** [comment]
> 
> 
> I downloaded v1.0.11 from git ppa and there were 2 versions. 1.0.12 and 1.0.11.
> I install it and w_scan2 -s ?
> and 124E and 128E were not in the list.
> I am running ubuntu and it seems the only available old version for ubuntu is 1.0.11.

I'm on Ubuntu too, so I quickly recompiled the latest version with the old satellites.dat file.  Even though transponders have changed since then, it may still work because once one transponder is successfully tuned to, information about other transponders is often received from the satellite.  So this version may help you out for now.  Please tell me if it does.

[w_scan2.zip](https://github.com/stefantalpalaru/w_scan2/files/6328047/w_scan2.zip)

**Comment by f520k510** [comment]
Thanks I scan with this version and can generate conf files now.
Many Thanks.

**Comment by andimik** [comment]
Well, I found for example

https://www.fastsatfinder.com/transponders_asia.html

https://www.satbeams.com/downloads

**Comment by jmwislez** [comment]
> 
> 
> Well, I found for example
> 
> https://www.fastsatfinder.com/transponders_asia.html
> 
> https://www.satbeams.com/downloads

Excellent, thank you!  I used this to update the satellites.dat file and autogeneration script in the above pull request.
