### ISSUE TITLE
DVB-C channels scan in South Asia- no country listings! 

### ISSUE THREAD

**Issue by siliconhippy** [stefantalpalaru/w_scan2#37]
Hi Stefan ! 

Looks quite recent with April updates.

My friends are running a test of dvb-C cable tv reception in South Asia. I am in Toronto.

We followed this useful guide, using a similar Transmeta DVB-T2/C USB dongle with a Sony CX DVB-C tv adapter being recognized ( along with Sony dvbt2 and Realtek dvbt2 tv adapters.)

(We are running Libreelec on a PC via USB boot.)

https://zedt.eu/tech/hardware/dvb-c-tv-raspberry-pi-libreeleckodi/

Unluckily because South Asia is not listed anywhere in the Tvheadend 4.2 version, we cannot run a scan to identify or download any channels.

And your readme says to input a country too.

Any workarounds ?
Do you think any tool here might help:
http://dtvtools.com

Thanks 😊
Shippy.

**Comment by stefantalpalaru** [comment]
Have you tried not setting the country? There is a default frequency list that kicks in.

**Comment by siliconhippy** [comment]
I didn't know.
Ok I will try, thanks ☺️
