### ISSUE TITLE
main:4007: FATAL: ***** NO USEABLE TERRESTRIAL CARD FOUND. *****

### ISSUE THREAD

**Issue by benb0jangles** [stefantalpalaru/w_scan2#38]
I have a problem when running w_scan2. I use:

w_scan2 -X -c GB

But i get error:

w_scan2 -X -c GB 
w_scan2-1.0.13 (compiled for DVB API 5.10)
https://github.com/stefantalpalaru/w_scan2

using settings for UNITED KINGDOM
DVB aerial
DVB-T GB
scan type TERRESTRIAL, delivery system SYS_UNDEFINED, channellist 6
output format czap/tzap/szap/xine
WARNING: could not guess your codepage. Falling back to 'UTF-8'
output charset 'UTF-8', use -C <charset> to override
Info: using DVB adapter auto detection.
main:4776: FATAL: ***** NO USEABLE TERRESTRIAL CARD FOUND. *****
Please check wether dvb driver is loaded and
verify that no dvb application (i.e. vdr) is running.

I try with three different usb adapters, but all same result.

When I run:

lsusb

it list whichever device is usb inserted

also

dmesg

it also displays device

System:
Ubuntu 18.04
Nvidia Jetson Nano

devices used:
RTL-SDR - Realtek Semiconductor Corp. RTL2838 DVB-T
Mirics msi001 / msi2500
Airspy mini - Rafael Micro R820T2 R860

I am able to use all three devices with SDR software such as gqrx/cubicsdr/sdr++

**Comment by stefantalpalaru** [comment]
The problem is not with w_scan2. You need kernel drivers (and sometimes firmware) for these sticks to work for DVB-T/DVB-T2. See:

https://www.linuxtv.org/wiki/index.php/DVB_via_USB

https://www.linuxtv.org/wiki/index.php/DVB-T_USB_Devices

https://www.linuxtv.org/wiki/index.php/DVB-T2_USB_Devices

**Comment by benb0jangles** [comment]
Thank you for reply :) 
Please can you tell do you know if you have seen working drivers used for any of my three USB devices?

I have Me-TV and W_Scan2 Compiled on my Jetson Nano Arm computer and i would like to scan for DVB-T / DVBT2 UK Freeview as first test, then try other things later.

devices used:
RTL-SDR - Realtek Semiconductor Corp. RTL2838 DVB-T
Mirics msi001 / msi2500
Airspy mini - Rafael Micro R820T2 R860
