### ISSUE TITLE
on the meaning of dvbsrc format

### ISSUE THREAD

**Issue by arielmol** [stefantalpalaru/w_scan2#46]
I have used the various format, however I understan the dvbsrc if GStreamer format, so far I got the output like this:

```
XHBUAP ;(null):183000:M10:A:0:81:83=eng;83:0:0:2:0:0:0:80
Canal 5 XEX-TDT;(null):473000:M10:A:0:49:51=spa,52=eng;51,52:0:0:1:0:0:0:48
MULTIMEDIOS;(null):479000:M10:A:0:49:52=ENG;52:0:0:1:0:0:0:48
MILENIO;(null):479000:M10:A:0:481=27:482=ENG;482:0:0:2:0:0:0:480
TELERITMO;(null):479000:M10:A:0:65=2:68=ENG;68:0:0:3:0:0:0:64
```

but dbvsrc ony uses 3 numbers as per the doc example:
`gst-launch-1.0 dvbsrc frequency=xxxxxxxxxxxx  delsys="atsc" modulation="8vsb" pids=48:49:52 `

So. **How to interpret the w_scan2 numbers to use in gstreamer dvbsrc ?**

**Comment by arielmol** [comment]
This is my full table (split by ':'), but I don't know how to go from that, to gstreamer dvbsrc format. Or what's the meaning of each column besides de obvious.

![image](https://user-images.githubusercontent.com/723830/182435017-f7850ea8-45ed-4536-b5e9-880cf92d25b7.png)

**Comment by stefantalpalaru** [comment]
Try the self-documenting VLC output, by using the "-L" option. You'll get something like:

```xml
                <track>
                        <title>0023. LA7 (provvisorio)</title>
                        <location>dvb-t://frequency=506000000</location>
                        <extension application="http://www.videolan.org/vlc/playlist/0">
                                <vlc:option>dvb-bandwidth=8</vlc:option>
                                <vlc:option>dvb-ts-id=263</vlc:option>
                                <vlc:id>24</vlc:id>
                                <vlc:option>program=721</vlc:option>
                        </extension>
                </track>
```

**Comment by arielmol** [comment]
So for example:

```
Las Estrellas XHTM-TDT;(null):605000:M10:A:0:49=2:51=spa,52=eng;51,52:0:0:1:0:0:0:48
XHTM;(null):605000:M10:A:0:65:67=spa;67:0:0:2:0:0:0:64
```
![image](https://user-images.githubusercontent.com/723830/182442203-37018c14-650e-4177-a083-c175f0c588ac.png)

Is equivalent to:

```
<track>
                        <title>2:1 Las Estrellas XHTM-TDT</title>
                        <location>atsc://frequency=605000000</location>
                        <extension application="http://www.videolan.org/vlc/playlist/0">
                                <vlc:option>dvb-modulation=8VSB</vlc:option>
                                <vlc:id>1</vlc:id>
                                <vlc:option>program=1</vlc:option>
                        </extension>
                </track>
                <track>
                        <title>2:2 XHTM</title>
                        <location>atsc://frequency=605000000</location>
                        <extension application="http://www.videolan.org/vlc/playlist/0">
                                <vlc:option>dvb-modulation=8VSB</vlc:option>
                                <vlc:id>1</vlc:id>
                                <vlc:option>program=2</vlc:option>
                        </extension>
                </track>
```
But i can't figure out what to insert on GStreamer dbvsrc.

**Comment by arielmol** [comment]
By reading `dbvsrc` i get

> gst-launch-1.0 dvbsrc frequency=503000000 delsys="atsc" modulation="8vsb" pids=48:49:52  <....>
> PMT ID 48, Audio/Video elementary stream PIDs 49 and 52 respectively

But the conf lines on w_scan2 have many more numbers. And VLC numbers do not really match.

**Comment by arielmol** [comment]
Turns out that using `dvbbasebin` is much easier and you only need the `dvbv5-channels.conf `
