### ISSUE TITLE
Channel number output from scan

### ISSUE THREAD

**Issue by btoconnor** [stefantalpalaru/w_scan2#47]
I just stumbled on to this fork of `w_scan` and I had a question - I see when I run `w_scan2` I get the expected channels - I am looking to capture the "Channel number" that is found during the end of the scan:

```
803000: 8VSB(time: 03:40.506)
tune to: 8VSB     f=201000 kHz (0:0:0) (time: 03:44.296)
service is running. Channel number: 13:1. Name: 'WJZ-TV '
service is running. Channel number: 13:2. Name: 'Start TV'
service is running. Channel number: 13:3. Name: 'Dabl   '
service is running. Channel number: 13:4. Name: 'FaveTV'
tune to: 8VSB     f=207000 kHz (0:0:0) (time: 03:47.806)
service is running. Channel number: 11:1. Name: 'WBAL-DT'
service is running. Channel number: 11:2. Name: 'MeTV'
service is running. Channel number: 54:3. Name: 'Comet'
service is running. Channel number: 54:4. Name: 'Stadium'
service is running. Channel number: 11:4. Name: 'TheGrio'
service is running. Channel number: 11:3. Name: 'Story'
```

So, for instance, I'd like to be able to reference that "WJZ-TV" has a channel number of "13.1" (`13:1` would be sufficient as well as obviously I can just parse that).  I see that "WJZ-TV" is in the resulting scan file, but I don't see the channel number or any obvious way to derive it from the information stored there.  Is there a way to reference that after the scan is complete?

I understand this is behavior that the original `w_scan` program had, but activity here seems much more recent.

**Comment by stefantalpalaru** [comment]
Implemented in the "master" branch. I'm assuming neither major nor minor channel numbers can have more than three digits each and I'm left-padding them with zeroes, so you can sort your VLC playlist by name and get channel number ordering.

I cannot test ATSC scanning myself, so please test and report any problems.
