### ISSUE TITLE
After scanning

### ISSUE THREAD

**Issue by y0rune** [stefantalpalaru/w_scan2#9]
Hi !
Thank you for doing it ;) BTW when i use w_scan i have only 15 channels when I use yours I have 30 channels. But VLC cant play .conf (via w_scan2)

**Comment by stefantalpalaru** [comment]
You need the XSPF output for VLC, which is turned on by the "-L" option.

This is how I do it: `w_scan2 -ft1 -c IT -E0 -O0 -t2 -L > channels.xspf`. Afterwards, I can watch TV using VLC: `vlc --dvb-adapter 0 --dvb-budget-mode channels.xspf`.

**Comment by y0rune** [comment]
okey okey Thank You I will try <3
